# Generated by Django 6.0.2 on 2026-04-13 17:54

import django.db.models.deletion
from django.db import migrations, models


def backfill_cover_photo(apps, schema_editor):
    Album = apps.get_model("albums", "Album")
    Photo = apps.get_model("albums", "Photo")

    for album in Album.objects.all():
        cover = (
            Photo.objects.filter(album=album, status="ready")
            .exclude(image="")
            .order_by("sort_order", "-uploaded_at")
            .first()
        )
        if cover:
            Album.objects.filter(pk=album.pk).update(cover_photo=cover)


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_alter_photo_options_photo_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_albums', to='albums.photo'),
        ),
        migrations.RunPython(backfill_cover_photo, migrations.RunPython.noop),
    ]
