# Generated by Django 6.0.2 on 2026-04-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_photo_image_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Meaningful description for screen readers and SEO.', max_length=300),
        ),
    ]
