apiVersion: batch/v1
kind: CronJob
metadata:
  name: s8njee-postgres-backup
spec:
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: registry-s8njee-pull
