apiVersion: v1
kind: ConfigMap
metadata:
  name: s8njee-web-config
data:
  DEBUG: "False"
  ENABLE_SSL: "True"
  ALLOWED_HOSTS: "blog.s8njee.com"
  CSRF_TRUSTED_ORIGINS: "https://blog.s8njee.com"
  DB_ENGINE: "django.db.backends.postgresql"
  DB_NAME: "s8njee"
  DB_HOST: "s8njee-postgres.s8njee-web.svc.cluster.local"
  DB_PORT: "5432"
  DB_BACKUP_BUCKET: "s8njee-photoblog"
  DB_BACKUP_PREFIX: "backups/postgres/netcup/s8njee"
  DB_BACKUP_EXCLUDED_TABLES: "django_session"
  AWS_STORAGE_BUCKET_NAME: "s8njee-photoblog"
  AWS_S3_REGION_NAME: "us-east-1"
  REDIS_URL: "redis://valkey:6379/1"
  CELERY_BROKER_URL: "redis://valkey:6379/0"
