apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: s8njee-web
resources:
  - namespace.yaml
  - ../../base
  - configmap.yaml
  - sealed-secret.yaml
  - registry-pull-sealed-secret.yaml
  - ingress.yaml
patches:
  - path: deployment-patch.yaml
  - path: backup-cronjob-patch.yaml
images:
  - name: s8njee-web
    newName: registry.s8njee.com/s8njee-web
    newTag: sha-e74d41d33b9568a2a13372804763304680ee7be5
