apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: s8njee-web
resources:
  - namespace.yaml
  - ../../base
  - configmap.yaml
  - sealed-secret.yaml
  - postgres-headless-service.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - registry-pull-sealed-secret.yaml
  - ingress.yaml
patches:
  - path: deployment-patch.yaml
  - path: backup-cronjob-patch.yaml
images:
  - name: s8njee-web
    newName: registry.s8njee.com/s8njee-web
    newTag: sha-75c292cf4b9cd8a383b86454ef93928ad6997478
