---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-s8njee-pull
  namespace: s8njee-web
spec:
  encryptedData:
    .dockerconfigjson: AgABwZtbsxgjNoC3wfhyDokb2dJXxJMoCffN1iokgNJ2fhPNF74mhCT9d+3MP4dwD1D9uW4buhCfkHKVmmJJyZ7pFciGnyyek86mcKvUZEe3X9+pG0UPC2Bn1yxwyzl6AH+5YhYnpVx5GYtLn8JxttiZszXKx4iTN2y+7hrgwtklPL0QAjrlDpx3D5mHPnAT3dcIULprid3NF7WslHCnL8q8FLiXiM4bD2R8C48zxM2peeBiF1NzQBcS80PKRt+1I5pMJ2/5WPK5bj20R+y+YAhs+JnYeOu2n2C2qoDNoRXCs8Z9DBPquCNmgEbMajSgvSEJ3S63aixhF+VpqhPjhpzwcLHsfc0hGBhBprZtPLMtXrWwM2HeEJsoJqpkuw3y8rGZmCleyJgjgxBfiej3NYiL5Vx/vEqaMn4Hyt9kImyVSwetqqdP9G1mcIkpoCGk0vcbY0taJK7jRGYaJ7lwyo7sBQ2A1FBGocQomfaS5HJeUVWivt9d8DqqiqU40Wa6dp7iecxJC9zkUSKASSbGjStw35817skfRiPURKZvov+fWaDICmrxeCIF68YYgoj1vthovXaWUlgn21CIOuhB8IcCt647gKmzewx5iJNOzEN/ElE/yg3B9HK14SgFia8dHjclQaqa7RyMGQ52Ir1mmD4UUO6EM/tYn+tUWN915n0H70asRFW1PA2qHgGxvTYxITZxIqUJVRKs53io92poom2DIujmYy/TCKnbf1V9DdFS9Bfmm0VL3UBVbBQItQirjAyFPzusMJ4hW/FdrNkq06f7OuONhWm6911izrP23Yua828RlI28jtNu2nlHyuVJ9RanoOF6UEV+SO7d5/NM5E1RK0mL+k5xicaEMkX5b0LIUwigqtW8K11Ljqz0/zcJRURnjLEC4vVdw/5bJE3MfUwL+lHrtTTFWFTQDEThn8LL2Hg/FaaTf8wXokfd2BVQdw==
  template:
    metadata:
      name: registry-s8njee-pull
      namespace: s8njee-web
    type: kubernetes.io/dockerconfigjson
