apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s8njee-web-secrets
spec:
  encryptedData:
    SECRET_KEY: AgReplaceWithKubeseal
    DB_USER: AgReplaceWithKubeseal
    DB_PASSWORD: AgReplaceWithKubeseal
    AWS_ACCESS_KEY_ID: AgReplaceWithKubeseal
    AWS_SECRET_ACCESS_KEY: AgReplaceWithKubeseal
  template:
    metadata:
      name: s8njee-web-secrets
    type: Opaque
