apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base
  - configmap.yaml
  - sealed-secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
images:
  - name: s8njee-web
    newName: 192.168.1.248:5001/s8njee-web
    newTag: 20260323-193649-amd64
