apiVersion: v1
kind: Service
metadata:
  name: s8njee-postgres
spec:
  clusterIP: 10.43.185.137
  selector:
    app: s8njee-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
