apiVersion: v1
kind: Service
metadata:
  name: s8njee-web
spec:
  $patch: replace
  type: LoadBalancer
  selector:
    app: s8njee-web
  ports:
    - name: http
      port: 4201
      targetPort: http
