apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      nodeSelector:
        kubernetes.io/hostname: freya
      containers:
        - name: valkey
          image: valkey/valkey:8-alpine
          imagePullPolicy: IfNotPresent
          args:
            - valkey-server
            - --appendonly
            - "no"
          ports:
            - name: redis
              containerPort: 6379
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
