apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s8njee-web-freya
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/s4njee/s8njee-django.git
    targetRevision: freya
    path: k8s/overlays/freya
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
