apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - argocd-image-updater-install.yaml
  - image-updater.yaml
  - freya-image-updater.yaml
  - image-updater-registry-secret-rbac.yaml
  - image-updater-registry-secret-rbac-freya.yaml
  - netcup-application.yaml
  - freya-application.yaml
  - argo-server-certificate.yaml
  - argo-server-servers-transport.yaml
  - argo-server-ingressroute.yaml
