# Generated by Django 6.0.2 on 2026-04-13 17:43

from django.db import migrations, models


def backfill_sort_order(apps, schema_editor):
    Photo = apps.get_model("albums", "Photo")
    Album = apps.get_model("albums", "Album")

    for album in Album.objects.all():
        photos = Photo.objects.filter(album=album).order_by("-uploaded_at", "-id")
        for sort_order, photo in enumerate(photos):
            Photo.objects.filter(pk=photo.pk).update(sort_order=sort_order)


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_photo_exif_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['sort_order', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='photo',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(backfill_sort_order, migrations.RunPython.noop),
    ]
